package com.stanete.chicfy;

/**
 * Created by @stanete
 */
public interface MockResponseBodies {

  String NO_USERS = "{\n" + "  \"results\": []\n" + "}";
  String TEN_USERS = "{\n"
      + "    \"results\": [\n"
      + "        {\n"
      + "            \"gender\": \"female\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"miss\",\n"
      + "                \"first\": \"liana\",\n"
      + "                \"last\": \"wiese\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"6917 blumenstraße\",\n"
      + "                \"city\": \"cochem-zell\",\n"
      + "                \"state\": \"brandenburg\",\n"
      + "                \"postcode\": 66646\n"
      + "            },\n"
      + "            \"email\": \"liana.wiese@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"goldenbird143\",\n"
      + "                \"password\": \"beretta\",\n"
      + "                \"salt\": \"HhVPFcAo\",\n"
      + "                \"md5\": \"7b55bcc9a422a3e1c39fdd6b4723963b\",\n"
      + "                \"sha1\": \"8a6a95cb0b6fc4e12ed5a833c6cbda1f6cbf3ac7\",\n"
      + "                \"sha256\": \"3d9854fa27576f1b839f375565209636f7f6db54b408d6c6fbc377f493b56c0b\"\n"
      + "            },\n"
      + "            \"dob\": \"1979-11-14 11:47:55\",\n"
      + "            \"registered\": \"2013-02-20 03:18:08\",\n"
      + "            \"phone\": \"0138-1418286\",\n"
      + "            \"cell\": \"0173-3388655\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"\",\n"
      + "                \"value\": null\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/women/49.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/women/49.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/women/49.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"DE\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"female\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"madame\",\n"
      + "                \"first\": \"mila\",\n"
      + "                \"last\": \"leclerc\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"8420 rue baraban\",\n"
      + "                \"city\": \"morges 1\",\n"
      + "                \"state\": \"zug\",\n"
      + "                \"postcode\": 9190\n"
      + "            },\n"
      + "            \"email\": \"mila.leclerc@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"heavybutterfly394\",\n"
      + "                \"password\": \"ravens\",\n"
      + "                \"salt\": \"yVlV3YNr\",\n"
      + "                \"md5\": \"10892ca95025aa83bc96e2f7e1384916\",\n"
      + "                \"sha1\": \"1c5c86e5847eaf81f79ac8c157d6ba99f55eea9a\",\n"
      + "                \"sha256\": \"c54965291c790f99a19ad16b0f23bfb55d0dac39d005b8f6aa43b5f5b55e0214\"\n"
      + "            },\n"
      + "            \"dob\": \"1980-12-04 00:50:35\",\n"
      + "            \"registered\": \"2008-09-08 15:48:52\",\n"
      + "            \"phone\": \"(191)-451-0577\",\n"
      + "            \"cell\": \"(683)-004-1713\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"AVS\",\n"
      + "                \"value\": \"756.YFOL.XPYJ.41\"\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/women/74.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/women/74.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/women/74.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"CH\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"male\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"mr\",\n"
      + "                \"first\": \"امیر\",\n"
      + "                \"last\": \"حسینی\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"1058 خالد اسلامبولی\",\n"
      + "                \"city\": \"بندرعباس\",\n"
      + "                \"state\": \"مازندران\",\n"
      + "                \"postcode\": 75747\n"
      + "            },\n"
      + "            \"email\": \"امیر.حسینی@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"heavydog483\",\n"
      + "                \"password\": \"sherman\",\n"
      + "                \"salt\": \"22K31YqW\",\n"
      + "                \"md5\": \"0141b92f02d590e2cafc892704e74491\",\n"
      + "                \"sha1\": \"c1f4ee4fb2c2707a3b293ab8a267ee745e0b67dd\",\n"
      + "                \"sha256\": \"95bff93e10a44098024f9232522c0aca496e36743cf8bc52d0db9970bbec4612\"\n"
      + "            },\n"
      + "            \"dob\": \"1949-09-27 04:41:12\",\n"
      + "            \"registered\": \"2005-02-26 03:41:18\",\n"
      + "            \"phone\": \"014-26854036\",\n"
      + "            \"cell\": \"0992-072-4810\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"\",\n"
      + "                \"value\": null\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/men/59.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/men/59.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/men/59.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"IR\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"male\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"mr\",\n"
      + "                \"first\": \"clarence\",\n"
      + "                \"last\": \"ferguson\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"7789 killarney road\",\n"
      + "                \"city\": \"newcastle west\",\n"
      + "                \"state\": \"louth\",\n"
      + "                \"postcode\": 50219\n"
      + "            },\n"
      + "            \"email\": \"clarence.ferguson@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"smallostrich499\",\n"
      + "                \"password\": \"kimber\",\n"
      + "                \"salt\": \"cwvsZ54p\",\n"
      + "                \"md5\": \"936f41a246b3a879ef536d82b4737a38\",\n"
      + "                \"sha1\": \"e38826d28bf25341a1ed1cbefb6d52f9bae17864\",\n"
      + "                \"sha256\": \"30d75ad9c353e0f56ba47de5a3382fc782ba6e3ecee8a929bce5a0591fcb18d7\"\n"
      + "            },\n"
      + "            \"dob\": \"1968-02-15 16:03:44\",\n"
      + "            \"registered\": \"2016-08-02 18:18:17\",\n"
      + "            \"phone\": \"031-919-3090\",\n"
      + "            \"cell\": \"081-630-1560\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"PPS\",\n"
      + "                \"value\": \"0393049T\"\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/men/50.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/men/50.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/men/50.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"IE\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"male\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"monsieur\",\n"
      + "                \"first\": \"elliot\",\n"
      + "                \"last\": \"jean\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"8274 rue de l'abbé-soulange-bodin\",\n"
      + "                \"city\": \"lussy-sur-morges\",\n"
      + "                \"state\": \"bern\",\n"
      + "                \"postcode\": 7341\n"
      + "            },\n"
      + "            \"email\": \"elliot.jean@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"yellowbird318\",\n"
      + "                \"password\": \"shanti\",\n"
      + "                \"salt\": \"nGjl4pfb\",\n"
      + "                \"md5\": \"693eb873f8d8fc5e9f318242a4c65a4a\",\n"
      + "                \"sha1\": \"69f31bc7f2010ccdc6a3b267589cfebc757468fd\",\n"
      + "                \"sha256\": \"17ae42b948c216edaf9c4942f02a87a7733f4f551455d7dc9f2fef679e5c3bc1\"\n"
      + "            },\n"
      + "            \"dob\": \"1950-04-30 22:50:05\",\n"
      + "            \"registered\": \"2005-12-31 20:18:07\",\n"
      + "            \"phone\": \"(089)-847-9895\",\n"
      + "            \"cell\": \"(178)-351-7585\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"AVS\",\n"
      + "                \"value\": \"756.MYCG.UKGQ.72\"\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/men/14.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/men/14.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/men/14.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"CH\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"male\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"mr\",\n"
      + "                \"first\": \"adem\",\n"
      + "                \"last\": \"çetin\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"2356 kushimoto sk\",\n"
      + "                \"city\": \"İzmir\",\n"
      + "                \"state\": \"uşak\",\n"
      + "                \"postcode\": 59361\n"
      + "            },\n"
      + "            \"email\": \"adem.çetin@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"brownostrich579\",\n"
      + "                \"password\": \"yong\",\n"
      + "                \"salt\": \"iETDABqK\",\n"
      + "                \"md5\": \"bbc02b1dc7f2be1a68e81660d9a1c916\",\n"
      + "                \"sha1\": \"918f16181e611035fcb4f35bd3aa6bb40e43a16b\",\n"
      + "                \"sha256\": \"3cecd50d1f66ef77d6f76869e7c52fe4bfd7120177c0bb84d66f9da5354b8909\"\n"
      + "            },\n"
      + "            \"dob\": \"1979-07-31 17:32:30\",\n"
      + "            \"registered\": \"2002-12-17 15:31:48\",\n"
      + "            \"phone\": \"(292)-664-9447\",\n"
      + "            \"cell\": \"(767)-463-2015\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"\",\n"
      + "                \"value\": null\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/men/71.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/men/71.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/men/71.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"TR\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"male\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"mr\",\n"
      + "                \"first\": \"fúlvio\",\n"
      + "                \"last\": \"nunes\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"9689 avenida brasil \",\n"
      + "                \"city\": \"santa maria\",\n"
      + "                \"state\": \"distrito federal\",\n"
      + "                \"postcode\": 85844\n"
      + "            },\n"
      + "            \"email\": \"fúlvio.nunes@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"heavykoala327\",\n"
      + "                \"password\": \"nintendo\",\n"
      + "                \"salt\": \"izLQXPWu\",\n"
      + "                \"md5\": \"e8539d3d00d58fb9628e77fe3e70ee4d\",\n"
      + "                \"sha1\": \"b734fff09218835a052843816d288e5c2a94360a\",\n"
      + "                \"sha256\": \"bf0e6e44056bf4d136c4ae4339ce689241187f817f9c03757a8ca132734a582c\"\n"
      + "            },\n"
      + "            \"dob\": \"1962-08-25 21:32:23\",\n"
      + "            \"registered\": \"2009-06-22 01:51:43\",\n"
      + "            \"phone\": \"(07) 7058-2686\",\n"
      + "            \"cell\": \"(60) 3722-3293\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"\",\n"
      + "                \"value\": null\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/men/49.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/men/49.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/men/49.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"BR\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"female\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"ms\",\n"
      + "                \"first\": \"özsu\",\n"
      + "                \"last\": \"dizdar\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"2142 tunalı hilmi cd\",\n"
      + "                \"city\": \"yozgat\",\n"
      + "                \"state\": \"amasya\",\n"
      + "                \"postcode\": 44320\n"
      + "            },\n"
      + "            \"email\": \"özsu.dizdar@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"bluekoala233\",\n"
      + "                \"password\": \"quant4307s\",\n"
      + "                \"salt\": \"CacokYqA\",\n"
      + "                \"md5\": \"597ebe495771f0c4440d2911468af719\",\n"
      + "                \"sha1\": \"dd2e90c34b2aaf93cb98b8a4baa0bc6a51b56341\",\n"
      + "                \"sha256\": \"f120886498121d39554c23d74c4fbfce9628de6d90cf2c3ec35a95a13d0d8487\"\n"
      + "            },\n"
      + "            \"dob\": \"1946-03-09 17:26:37\",\n"
      + "            \"registered\": \"2006-09-16 04:26:38\",\n"
      + "            \"phone\": \"(035)-233-2556\",\n"
      + "            \"cell\": \"(059)-513-8137\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"\",\n"
      + "                \"value\": null\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/women/40.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/women/40.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/women/40.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"TR\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"female\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"miss\",\n"
      + "                \"first\": \"leiliane\",\n"
      + "                \"last\": \"da rosa\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"6203 rua dezessete \",\n"
      + "                \"city\": \"anápolis\",\n"
      + "                \"state\": \"santa catarina\",\n"
      + "                \"postcode\": 16478\n"
      + "            },\n"
      + "            \"email\": \"leiliane.darosa@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"beautifulcat902\",\n"
      + "                \"password\": \"barbados\",\n"
      + "                \"salt\": \"xpF1RjXo\",\n"
      + "                \"md5\": \"c6a7aed48038e850db1bcf9d7b3d8adb\",\n"
      + "                \"sha1\": \"4289efe48c797224c7dc27642dff697b6638e757\",\n"
      + "                \"sha256\": \"28b558c5c7b4121c538202408cdfaea604496dc9559d8f2f97e67b11003837af\"\n"
      + "            },\n"
      + "            \"dob\": \"1965-03-05 08:43:06\",\n"
      + "            \"registered\": \"2013-01-09 05:49:02\",\n"
      + "            \"phone\": \"(20) 0386-4408\",\n"
      + "            \"cell\": \"(25) 0258-1125\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"\",\n"
      + "                \"value\": null\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/women/94.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/women/94.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/women/94.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"BR\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"gender\": \"male\",\n"
      + "            \"name\": {\n"
      + "                \"title\": \"mr\",\n"
      + "                \"first\": \"احسان\",\n"
      + "                \"last\": \"احمدی\"\n"
      + "            },\n"
      + "            \"location\": {\n"
      + "                \"street\": \"1598 سبلان جنوبی\",\n"
      + "                \"city\": \"همدان\",\n"
      + "                \"state\": \"خراسان جنوبی\",\n"
      + "                \"postcode\": 87752\n"
      + "            },\n"
      + "            \"email\": \"احسان.احمدی@example.com\",\n"
      + "            \"login\": {\n"
      + "                \"username\": \"purpleswan953\",\n"
      + "                \"password\": \"jjjjjj\",\n"
      + "                \"salt\": \"tnlDjjBs\",\n"
      + "                \"md5\": \"40a56637758a9a71f35f4161f8052fc0\",\n"
      + "                \"sha1\": \"095f18ff3bc27831526c6bc4a7d317bcc90b583c\",\n"
      + "                \"sha256\": \"5764bdd85eb66e5f77fc80f0bb4165481ded553f2db8cb4386e665fdf5f8d22c\"\n"
      + "            },\n"
      + "            \"dob\": \"1992-07-25 14:29:52\",\n"
      + "            \"registered\": \"2004-04-18 01:18:32\",\n"
      + "            \"phone\": \"013-70561122\",\n"
      + "            \"cell\": \"0965-065-7580\",\n"
      + "            \"id\": {\n"
      + "                \"name\": \"\",\n"
      + "                \"value\": null\n"
      + "            },\n"
      + "            \"picture\": {\n"
      + "                \"large\": \"https://randomuser.me/api/portraits/men/26.jpg\",\n"
      + "                \"medium\": \"https://randomuser.me/api/portraits/med/men/26.jpg\",\n"
      + "                \"thumbnail\": \"https://randomuser.me/api/portraits/thumb/men/26.jpg\"\n"
      + "            },\n"
      + "            \"nat\": \"IR\"\n"
      + "        }\n"
      + "    ],\n"
      + "    \"info\": {\n"
      + "        \"seed\": \"2060718dd273a9e3\",\n"
      + "        \"results\": 10,\n"
      + "        \"page\": 1,\n"
      + "        \"version\": \"1.1\"\n"
      + "    }\n"
      + "}";

}
